name: 'Chromatic'

on: push

jobs:
  test-and-publish-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # by default, it only retrieves the last commit
          # Chromatic must have the history to work only on modified files
          # https://www.chromatic.com/docs/github-actions#support-for-codeactionscheckoutv2code-and-above
          # we don't need to have the full history
          # set fetch-depth to an arbitrary number large enough to contain all commits from the main branch
          fetch-depth: '100'
      - name: Install dependencies
        run: yarn
      - name: Build Storybook
        run: yarn build-storybook --output-dir /tmp/${{ github.sha }}
      - name: Run axe storybook accessibility tests
        run: yarn axe-storybook --build-dir /tmp/${{ github.sha }}
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: /tmp/${{ github.sha }}
          onlyChanged: true
